# Generated by Django 6.0.6 on 2026-06-11 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tutorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='cubiculo',
        ),
    ]
