# Generated by Django 6.0.6 on 2026-06-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_tutorias", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tutor",
            options={"verbose_name": "Tutor", "verbose_name_plural": "Tutores"},
        ),
        migrations.AlterModelOptions(
            name="tutoria",
            options={"verbose_name": "Tutoría", "verbose_name_plural": "Tutorías"},
        ),
        migrations.RenameField(
            model_name="tutoria",
            old_name="fecha_hora",
            new_name="fecha",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="cubiculo",
        ),
        migrations.AddField(
            model_name="tutoria",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aceptada", "Aceptada"),
                    ("rechazada", "Rechazada"),
                    ("finalizada", "Finalizada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
