# Generated by Django 6.0.6 on 2026-06-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tutorias', '0002_alter_tutor_options_remove_tutor_cubiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutoria',
            options={'verbose_name': 'Tutoría', 'verbose_name_plural': 'Tutorías'},
        ),
        migrations.RenameField(
            model_name='tutoria',
            old_name='fecha_hora',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='tutoria',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20),
        ),
    ]
