# Generated by Django 4.2.30 on 2026-06-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_tutorias", "0002_alter_tutor_options_alter_tutoria_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materia",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tutoria",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
