# Generated by Django 4.2.19 on 2026-06-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "ci",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("paterno", models.CharField(max_length=50)),
                ("materno", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "rol",
                    models.CharField(
                        choices=[("EST", "Estudiante"), ("TUT", "Tutor")], max_length=3
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="gestion_tutorias.persona",
                    ),
                ),
                ("carrera", models.CharField(max_length=100)),
                ("codigo_estudiante", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="gestion_tutorias.persona",
                    ),
                ),
                ("especialidad", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tutor",
                "verbose_name_plural": "Tutores",
            },
        ),
        migrations.CreateModel(
            name="Tutoria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_tutorias.materia",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_tutorias.estudiante",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_tutorias.tutor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutoría",
                "verbose_name_plural": "Tutorías",
            },
        ),
    ]
